### ISSUE TITLE
아기 일러스트 제작

### ISSUE THREAD

**Issue by sohn126** [ILLIONAIRE-SOFT/CocoaBaby#10]
아기 일러스트 20개 제작

**Comment by iluvdadong** [comment]
> 이번주 주말에 5개 빼기

**Comment by iluvdadong** [comment]
* ~~~아이콘~~~
### 홈
* ~~~배경 오전/해질녘/ 밤~~~ (홈)
* ~~~이름 레이블 내리기~~~
* 아기 10개
### 다이어리
* ~~~다이어리 게시물 목록에서 아빠 댓글있을 시 조그만 표시 -> 하트~~~
* ~~~다이어리 클릭시 아빠댓글창 -> 긴 말풍선 / 아빠 얼굴 -> 하트~~~
* ~~~데이트 피커뷰 클릭시 나타나는 피커뷰창 유아이조절~~~
### 팁스
* ~~~뷰 코너레디우스 주고, 색상밝게 조절~~~
### 설정
*~~~ 레이아웃 다시짜서 위치 조정 아이콘으로 표현~~~ -> 테이블 뷰로 변경

**Comment by iluvdadong** [comment]
1~4주차 <-이런식으로 총 Tips 10페이지로 줄이기
(현재 : 40 페이지)

**Comment by iluvdadong** [comment]
* 맨 처음 로그인 화면 (페이스북/구글 로그인)
* 축하합니다 일러스트 완료
* 아기 10개 
* 캡쳐시 화면 시간별로 2개 더 그리기, 밤/노멀
* 팁스 - 줄간격 변경
* 팁스 - 파파 마마 -> Mom Dad로 변경
* 카메라 가이드 -> 영어로
