### ISSUE TITLE
탭 왔다 갔다 거리면 홈에서 mamatitle 받아오는 부분이 비어져있음

### ISSUE THREAD

**Issue by iluvdadong** [ILLIONAIRE-SOFT/CocoaBaby#90]
1주차에는 5대 영양소를 골고루! 라고 나왔다가도 
탭 왔다갔다 거리면 다시 mama title 로 바꼈다가 좀 지나면,
1주차에는 5대 영양소 블라블라~ 로 다시 나옴.

왜 일까?
파베에서 데이터 받아오는게 늦어서 그런가?

**Comment by LeFal** [comment]
버그가 아니라 기능임미다 

엄마면 애기 정보나 엄마 정보가 둘중 하나 랜덤으로 
아빠면 애기정보나 아빠정보가 둘중하나 랜덤으로 나옵니다
